## Pre-commit setup
# See https://github.com/python-discord/code-jam-template/tree/main#pre-commit-run-linting-before-committing
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# pre-commit run --all-file

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        args: [--line-length=119]

  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: v2.5.0
  #   hooks:
  #     - id: reorder-python-imports

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.2
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations~=2.6.2
          - flake8-bandit~=2.1
          - flake8-docstrings~=1.6
          - flake8-isort~=4.0

  # - repo: https://github.com/PyCQA/pylint
  #   rev: v2.9.3
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       # entry: pylint
  #       # language: system
  #       types: [python]
  #       always_run: true
  #       args: [--disable=C0103]

  # - repo: local
  #   hooks:
  #     - id: isort
  #       name: ISort
  #       entry: python -m isort .  # Default Env setup
  #       # entry: pipenv run python -m isort .  # Pipenv setup
  #       # entry: poetry run python -m isort .  # Poetry setup
  #       language: system
  #       types: [python]
  #       require_serial: true
  #     - id: flake8
  #       name: Flake8
  #       entry: python -m flake8  # Default Env setup
  #       # entry: pipenv run python -m flake8  # Pipenv setup
  #       # entry: poetry run python -m flake8  # Poetry setup
  #       language: system
  #       types: [python]
  #       require_serial: true
  #       # args: [--max-line-length=119]
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types: [python]
  #       # always_run: true
  #       # args: [--disable=C0103]
